### ISSUE TITLE
Tinderbox manual test cases need to be updated

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#142]
On using the test cases for a bug fix, I noticed that some of them do not work, but the cause was unrelated to my fix. I think we need to update that list. The results I found are shown below:

> mozdownload -a firefox -t tinderbox -p win32 --branch=mozilla-central -l el
> 
> Traceback (most recent call last):
>   File "scraper.py", line 960, in <module>
>     cli()
>   File "scraper.py", line 957, in cli
>     build.download()
>   File "scraper.py", line 237, in download
>     if os.path.isfile(os.path.abspath(self.target)):
>   File "scraper.py", line 197, in target
>     self.build_filename(self.binary))
>   File "scraper.py", line 148, in binary
>     self.path)
> **main**.NotFoundError: Binary not found in folder: https://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-central-l10n

the el locale does not exist

> mozdownload -a firefox -t tinderbox -p win32 --branch=mozilla-central --date=2013-07-17
> 
> Retrieving list of builds from https://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-central-win32
> Traceback (most recent call last):
>   File "scraper.py", line 960, in <module>
>     cli()
>   File "scraper.py", line 955, in cli
>     build = BUILD_TYPES[options.type](**kwargs)
>   File "scraper.py", line 643, in **init**
>     Scraper.**init**(self, _args, *_kwargs)
>   File "scraper.py", line 109, in **init**
>     self.get_build_info()
>   File "scraper.py", line 667, in get_build_info
>     self.build_index)
>   File "scraper.py", line 754, in get_build_info_for_index
>     raise NotFoundError(message, url)
> **main**.NotFoundError: No builds have been found: https://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-central-win32`

This is due to the builds getting out of date and removed at some point. We would need to mark in the test case that it is necessary to find your own valid dates to test them.

This is also applicable to timestamps, of course.

---

Suitable tests for Issue #138 need to be added, too

**Comment by whimboo** [comment]
Manual testcases are listed at https://github.com/mozilla/mozdownload/blob/master/tests/test_cases.md. So it would be good to check what needs to be done here. If there are remaining tests to write lets do it.
