### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip' when downloading a file via direct scraper

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#176]
$ mozdownload --url https://bug911048.bugzilla.mozilla.org/attachment.cgi?id=811671
  INFO | Downloading from: https://bug911048.bugzilla.mozilla.org/attachment.cgi?id=811671
Traceback (most recent call last):
  File "/home/henrik/.virtualenvs/mozdownload/bin/mozdownload", line 9, in <module>
    load_entry_point('mozdownload==1.9', 'console_scripts', 'mozdownload')()
  File "/mozilla/code/mozdownload/mozdownload/scraper.py", line 1007, in cli
    build.download()
  File "/mozilla/code/mozdownload/mozdownload/scraper.py", line 277, in download
    total_size = int(r.headers.get('Content-length').strip())
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by whimboo** [comment]
The fix for issue #198 landed a while ago and this is fixed.
