### ISSUE TITLE
Don't run local http server for tests on port 8080

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#179]
I'm colliding with this issue once in a while, majorly when I also work on Jenkins stuff beside. It's also using port 8080 for the webserver part. So our tests cannot be run because the port is in use.

Can we please get a free port instead of specifying a hard-coded one?

**Comment by Nebelhom** [comment]
@whimboo 

I just tried your suggestion and had the following error. This happened both on defining `port=0` in `MozHttpdBaseTest`` and on removing the parameter entirely (in `mozhttpd_base_test.py`, of course)

```
======================================================================
ERROR: test_scraper (test_invalid_changeset.TestTryScraper_invalidParameters)
Testing download scenarios with invalid parameters for TryScraper
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/tests/try_scraper/test_invalid_changeset.py", line 36, in test_scraper
    **entry['args'])
  File "/usr/lib/python2.7/unittest/case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/mozdownload/scraper.py", line 950, in __init__
    Scraper.__init__(self, *args, **kwargs)
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/mozdownload/scraper.py", line 144, in __init__
    self.get_build_info()
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/mozdownload/scraper.py", line 955, in get_build_info
    self.builds, self.build_index = self.get_build_info_for_index()
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/mozdownload/scraper.py", line 1009, in get_build_info_for_index
    timeout=self.timeout_network)
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/mozdownload/parser.py", line 28, in __init__
    headers=headers, timeout=self.timeout)
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/tmp/venv/local/lib/python2.7/site-packages/requests-1.2.2-py2.7.egg/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/tmp/venv/local/lib/python2.7/site-packages/requests-1.2.2-py2.7.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/tmp/venv/local/lib/python2.7/site-packages/requests-1.2.2-py2.7.egg/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/tmp/venv/local/lib/python2.7/site-packages/requests-1.2.2-py2.7.egg/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/home/nebelhom/Mozilla/mozdownload/mozdownload/tmp/venv/local/lib/python2.7/site-packages/requests-1.2.2-py2.7.egg/requests/adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /data/firefox/try-builds (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

----------------------------------------------------------------------
Ran 21 tests in 11.875s

FAILED (errors=12)
Traceback (most recent call last):
  File "./run_tests.py", line 92, in <module>
    python(os.path.join('tests', 'test.py'))
  File "./run_tests.py", line 40, in python
    check_call(pypath + list(args))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/nebelhom/Mozilla/mozdownload/mozdownload/tmp/venv/bin/python', 'tests/test.py']' returned non-zero exit status 1
```

**Comment by whimboo** [comment]
So does it mean the webserver tries to setup a socket at port 80 by default when you omit this parameter or specify 0? Is something else running on this port? Or is the firewall blocking it?

**Comment by jamesfrye420** [comment]
> I'm colliding with this issue once in a while, majorly when I also work on Jenkins stuff beside. It's also using port 8080 for the webserver part. So our tests cannot be run because the port is in use.
> 
> Can we please get a free port instead of specifying a hard-coded one?

Umm hey, I am new to all this bug fixing stuff but I would like to trynna fix this, can you guide me as to where shall I get the code to begin with?

**Comment by jamesfrye420** [comment]
I think I have a possible fix to this but when I trynna test the conftest.py file using tox I get this error, any idea as to why this happens? @whimboo @Nebelhom 
`ERROR: InvocationError for command /home/user/Downloads/Firefox-bugs-source-code-download/mozdownload/.tox/py39/bin/pytest --verbose --cov -k tests/conftest.py (exited with code 5)`
