### ISSUE TITLE
Old nightly builds aren't downloaded because they are located under 'trunk'

### ISSUE THREAD

**Issue by aleksejrs** [mozilla/mozdownload#182]
$ mozdownload -t daily --date=2008-02-20 -p linux
(works)
$ mozdownload -t daily --date=2008-02-19 -p linux
Retrieving list of builds from https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2008/02
Traceback (most recent call last):
  File "…/virtualenv/bin/mozdownload", line 9, in <module>
    load_entry_point('mozdownload==1.9', 'console_scripts', 'mozdownload')()
  File "…/virtualenv/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 980, in cli
    build = BUILD_TYPES[options.type](**kwargs)
  File "…/virtualenv/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 325, in __init__
    Scraper.__init__(self, *args, **kwargs)
  File "…/virtualenv/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 110, in __init__
    self.get_build_info()
  File "…/virtualenv/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 349, in get_build_info
    self.date, build_index=self.build_index)
  File "…/virtualenv/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 418, in get_build_info_for_date
    raise NotFoundError(message, url)

For 20, it finds https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2008/02/2008-02-20-02-mozilla-central/, but for 19 and before, there is only https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2008/02/2008-02-19-04-trunk/

**Comment by whimboo** [comment]
I don't think it is a good investment of time to get this fixed. The use of such old nightlies will be very very low, and in those cases they could be manually downloaded.
