### ISSUE TITLE
Support downloading from sites with optional authentication

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozdownload#195]
It seems that if we provide `(None, None)` as auth for a site that supports optional authentication, such as Jenkins, we get an authorization required response.

> $ mozdownload --url=https://ci.mozilla.org/
  INFO | Downloading from: https://ci.mozilla.org/
Traceback (most recent call last):
  File "/Users/dhunt/.virtualenvs/mozdownload/bin/mozdownload", line 8, in <module>
    load_entry_point('mozdownload==1.10', 'console_scripts', 'mozdownload')()
  File "/Users/dhunt/workspace/mozdownload/mozdownload/scraper.py", line 1016, in cli
    build.download()
  File "/Users/dhunt/workspace/mozdownload/mozdownload/scraper.py", line 274, in download
    r.raise_for_status()
  File "/Users/dhunt/.virtualenvs/mozdownload/lib/python2.7/site-packages/requests-1.2.2-py2.7.egg/requests/models.py", line 689, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Authorization Required

We should provide None for the auth argument rather than a tuple with None values. We also need a test for this, which might require a new entry in mozqa.com.

**Comment by whimboo** [comment]
PR #230 got landed earlier today. So this will be available with the next 1.13 release.
