### ISSUE TITLE
One-time Authentication error in run_tests.py

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#256]
I came across an unrepeatable error when running `./run_tests.py` for PR #254 . I could not repeat it afterwards (tests ran fine), and it appears to be an unrelated issue. Nonetheless, I wanted to make everyone aware of it.

Could this be an issue in the future?

```
#################
# Running tests #
#################

test_authentication (test_base_scraper.BaseScraperTest)
testing with basic authentication ... ok
test_download (test_base_scraper.BaseScraperTest)
Test download method ... ok
test_notimplementedexceptions (test_base_scraper.BaseScraperTest) ... ok
test_optional_authentication (test_base_scraper.BaseScraperTest)
testing with optional basic authentication ... ERROR
test_platform_regex (test_base_scraper.BaseScraperTest)
Test for correct platform_regex output ... ok
test_scraper (test_daily_scraper.DailyScraperTest)
Testing various download scenarios for DailyScraper ... ok
test_scraper (test_invalid_date.TestDailyScraper_invalidParameters)
Testing download scenarios with invalid parameters for DailyScraper ... ERROR
test_build_indices (test_daily_indices.DailyScraperTest_indices)
Testing for correct build_index in DailyScraper ... ERROR
test_url_download (test_direct_scraper.TestDirectScraper) ... ok
test_filter (test_directory_parser.DirectoryParserTest)
Testing the DirectoryParser filter method ... ok
test_init (test_directory_parser.DirectoryParserTest)
Testing the basic functionality of the DirectoryParser Class ... ok
test_scraper (test_release_candidate_scraper.ReleaseCandidateScraperTest)
Testing various download scenarios for ReleaseCandidateScraper ... ok
test_build_indices (test_release_candidate_scraper_indices.ReleaseCandidateScraperTest_build_indices)
Testing indices in choosing builds for ReleaseCandidateScraper ... ok
test_scraper (test_release_scraper.ReleaseScraperTest)
Testing various download scenarios for ReleaseScraper ... ok
test_scraper (test_tinderbox_scraper.TinderboxScraperTest)
Testing various download scenarios for TinderboxScraper ... ok
test_scraper (test_invalid_date.TestDailyScraper_invalidParameters)
Testing download scenarios with invalid parameters for DailyScraper ... ok
test_scraper (test_invalid_date.TestTinderboxScraper_invalidParameters)
Testing download scenarios with invalid parameters for TinderboxScraper ... ok
test_scraper (test_try_scraper.TryScraperTest)
Testing various download scenarios for TryScraper ... ok
test_scraper (test_invalid_changeset.TestTryScraper_invalidParameters)
Testing download scenarios with invalid parameters for TryScraper ... ok

======================================================================
ERROR: test_optional_authentication (test_base_scraper.BaseScraperTest)
testing with optional basic authentication
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nebelhom/Mozilla-Dev/mozdownload/src/mozdownload/tests/mozhttpd_base_test.py", line 40, in setUp
    self.httpd.start(block=False)
  File "/home/nebelhom/Mozilla-Dev/mozdownload/src/mozdownload/tmp/venv/local/lib/python2.7/site-packages/mozhttpd/mozhttpd.py", line 234, in start
    self.httpd = EasyServer((self.host, self.port), self.handler_class)
  File "/usr/lib/python2.7/SocketServer.py", line 408, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

======================================================================
ERROR: test_scraper (test_invalid_date.TestDailyScraper_invalidParameters)
Testing download scenarios with invalid parameters for DailyScraper
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nebelhom/Mozilla-Dev/mozdownload/src/mozdownload/tests/mozhttpd_base_test.py", line 40, in setUp
    self.httpd.start(block=False)
  File "/home/nebelhom/Mozilla-Dev/mozdownload/src/mozdownload/tmp/venv/local/lib/python2.7/site-packages/mozhttpd/mozhttpd.py", line 234, in start
    self.httpd = EasyServer((self.host, self.port), self.handler_class)
  File "/usr/lib/python2.7/SocketServer.py", line 408, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

======================================================================
ERROR: test_build_indices (test_daily_indices.DailyScraperTest_indices)
Testing for correct build_index in DailyScraper
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nebelhom/Mozilla-Dev/mozdownload/src/mozdownload/tests/mozhttpd_base_test.py", line 40, in setUp
    self.httpd.start(block=False)
  File "/home/nebelhom/Mozilla-Dev/mozdownload/src/mozdownload/tmp/venv/local/lib/python2.7/site-packages/mozhttpd/mozhttpd.py", line 234, in start
    self.httpd = EasyServer((self.host, self.port), self.handler_class)
  File "/usr/lib/python2.7/SocketServer.py", line 408, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

----------------------------------------------------------------------
Ran 19 tests in 17.503s

FAILED (errors=3)
Traceback (most recent call last):
  File "./run_tests.py", line 92, in <module>
    python(os.path.join('tests', 'test.py'))
  File "./run_tests.py", line 40, in python
    check_call(pypath + list(args))
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/nebelhom/Mozilla-Dev/mozdownload/src/mozdownload/tmp/venv/bin/python', 'tests/test.py']' returned non-zero exit status 1
```

**Comment by whimboo** [comment]
Looks like the mozhttpd process was still running in the background, or another tool used exactly the same port? It might be better to not hard-code our HTTP port of the local web server but choose a free one instead.

**Comment by Ethcelon** [comment]
@whimboo It's because mozhttpd_base_test has a hard coded port number (8080). I was able to replicate it by running another service on the same port. But the funny thing is for me every test failed except test_url_download which does not inherit from mhttpd.MozHttpdBaseTest. But @Nebelhom 's run shows other tests running.

**Comment by whimboo** [comment]
@Nebelhom were you able to reproduce that with further testruns? Or did this really happen only once?

**Comment by Nebelhom** [comment]
@whimboo @Ethcelon 

I repeated the test about 6 or 7 more times and it did not occur, which was odd. At that point, I went and reported the issue in case it occurs with someone else.

That way, we would know if this was just a freak occurrence or a true bug that was intermittent and hard to catch.

So to answer your question, no, I was not able to reproduce it.

Btw. we do already have an issue assigned to our port 8080 "issue". It's #179 . Maybe we should implement this change finally.

**Comment by whimboo** [comment]
If that really happened only once I strongly assume it was a side-effect on your machine and that this port was partly in use while the tests were running. Given that some tests passed it should have been acquired and freed quickly. It's strange but I do not have another explanation for it yet. Issue #179 would be good to get fixed. @Ethcelon would you try that?

**Comment by Ethcelon** [comment]
I'd love to! @whimboo: what should be our strategy for choosing a free
port? Will this be a change to the server code or the test code?

On Fri, Feb 20, 2015 at 12:22 PM, Henrik Skupin <notifications@github.com>
wrote:

> If that really happened only once I strongly assume it was a side-effect
> on your machine and that this port was partly in use while the tests were
> running. Given that some tests passed it should have been acquired and
> freed quickly. It's strange but I do not have another explanation for it
> yet. Issue #179 <https://github.com/mozilla/mozdownload/issues/179> would
> be good to get fixed. @Ethcelon <https://github.com/Ethcelon> would you
> try that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/mozdownload/issues/256#issuecomment-75197247>.
>



-- 

Om Bhallamudi
about.me/Om.Bhallamudi
[image: Om Bhallamudi on about.me]
  <http://about.me/Om.Bhallamudi>

**Comment by davehunt** [comment]
I believe if you pass 0 as the port a random free port will be selected by the server.

**Comment by whimboo** [comment]
@Ethcelon I would suggest we head over to issue #179 and leave this issue alone for now. Not sure if we will see it again. Otherwise what @davehunt suggested sounds fine! Let me know on issue #179 if you want to still work on it. Thanks.

**Comment by whimboo** [comment]
Given that #179 is fixed now lets mark this issue as WFM.
