### ISSUE TITLE
--destination option fails if only a filename is specified

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#267]
$ mozdownload -v latest --destination firefox.tar.bz2
Traceback (most recent call last):
  File "/home/henrik/.virtualenvs/fxtests/bin/mozdownload", line 9, in <module>
    load_entry_point('mozdownload==1.14', 'console_scripts', 'mozdownload')()
  File "/home/henrik/.virtualenvs/fxtests/lib/python2.7/site-packages/mozdownload/scraper.py", line 1256, in cli
    build.download()
  File "/home/henrik/.virtualenvs/fxtests/lib/python2.7/site-packages/mozdownload/scraper.py", line 295, in download
    os.makedirs(directory)
  File "/home/henrik/.virtualenvs/fxtests/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''

We want to enhance that option so it automatically uses the current active directory to store the file to.

**Comment by whimboo** [comment]
@ujjwalwahi would you be interested to work on that part, given that you implemented the original code?

**Comment by ujjwalwahi** [comment]
@whimboo yes sure, I will work on this

**Comment by whimboo** [comment]
Great! Please make also sure to add an additional test for it beside the currently existing ones. Thanks.

**Comment by whimboo** [comment]
#274 fixed this issue.
