### ISSUE TITLE
Does not work after mozregression is installed: requires pkg_resources ==1.2.2

### ISSUE THREAD

**Issue by aleksejrs** [mozilla/mozdownload#276]
Debian jessie/sid, virtualenv.  Started weeks or months ago, if not longer.  Reinstalling virtualenv does not help.

```
$ pip install --upgrade mozregression

$ mozdownload 
Traceback (most recent call last):
  File "/envs/mze/bin/mozdownload", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/envs/mze/local/lib/python2.7/site-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/envs/mze/local/lib/python2.7/site-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/envs/mze/local/lib/python2.7/site-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/envs/mze/local/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests==1.2.2
```

After re-installing mozdownload, mozregression breaks:
```
pkg_resources.DistributionNotFound: requests>=2.5.0
```

Debian jessie/sid has a package v5.5.1-1; experimental has 12.2-1.

**Comment by parkouss** [comment]
hmm, I think this will be fixed with issue #271.

**Comment by parkouss** [comment]
As a workaround, you can use one virtualenv folder for mozregression, and one other for mozdownload (if you use virtualenv).

**Comment by whimboo** [comment]
@parkouss is right. You should use different virtualenvs as best to avoid those conflicts. I will close this issue in favor of issue #271.

**Comment by whimboo** [comment]
PR #276 bumped requests to 2.7.0. It should work now.
