### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getLogger'

### ISSUE THREAD

**Issue by crdoconnor** [mozilla/mozdownload#299]
This error occurs on the latest (master) version of mozdownload::

    Traceback (most recent call last):
      File "/home/user/.local/bin/mozdownload", line 9, in <module>
        load_entry_point('mozdownload==1.16', 'console_scripts', 'mozdownload')()
      File "/home/user/.local/venvs/mozdownload/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 1248, in cli
        build = BUILD_TYPES[options.type](**kwargs)
      File "/home/user/.local/venvs/mozdownload/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 592, in __init__
        Scraper.__init__(self, *args, **kwargs)
      File "/home/user/.local/venvs/mozdownload/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 107, in __init__
        self.logger = mozlog.getLogger(' ')
     AttributeError: 'module' object has no attribute 'getLogger'

It looks like the latest version of mozlog no longer supports the API mozdownload is trying to use.

**Comment by whimboo** [comment]
PR #300 actually fixed the breakage with `getLogger()` due to API changes. But I still wonder to get rid of mozlog and simply use the `logging` module. I will have a look into it.

**Comment by whimboo** [comment]
I will push the follow-up through another issue. Marking that one as fixed.
