### ISSUE TITLE
mozdownload does not download files for android

### ISSUE THREAD

**Issue by vaibhavmagarwal** [mozilla/mozdownload#315]
Here is the traceback I receive when I try to download mozinfo.json for android:
```
$ mozdownload -t tinderbox --ext mozinfo.json -p android-x86
Traceback (most recent call last):
  File "/usr/local/bin/mozdownload", line 9, in <module>
    load_entry_point('mozdownload==1.17', 'console_scripts', 'mozdownload')()
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 1241, in cli
    build = BUILD_TYPES[options.type](**kwargs)
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 749, in __init__
    Scraper.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 130, in __init__
    self.get_build_info()
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 777, in get_build_info
    self.build_index)
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 872, in get_build_info_for_index
    url = urljoin(self.base_url, self.build_list_regex)
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 816, in build_list_regex
    'PLATFORM': '' if self.locale_build else self.platform_regex,
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 928, in platform_regex
    return PLATFORM_FRAGMENTS[self.platform]
KeyError: 'android-x86'
```
```
$ mozdownload -t tinderbox --ext mozinfo.json -p android-api-11
Traceback (most recent call last):
  File "/usr/local/bin/mozdownload", line 9, in <module>
    load_entry_point('mozdownload==1.17', 'console_scripts', 'mozdownload')()
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 1241, in cli
    build = BUILD_TYPES[options.type](**kwargs)
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 749, in __init__
    Scraper.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 130, in __init__
    self.get_build_info()
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 777, in get_build_info
    self.build_index)
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 872, in get_build_info_for_index
    url = urljoin(self.base_url, self.build_list_regex)
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 816, in build_list_regex
    'PLATFORM': '' if self.locale_build else self.platform_regex,
  File "/usr/local/lib/python2.7/site-packages/mozdownload-1.17-py2.7.egg/mozdownload/scraper.py", line 928, in platform_regex
    return PLATFORM_FRAGMENTS[self.platform]
KeyError: 'android-api-11'

```

**Comment by whimboo** [comment]
There is no Firefox for Android, but Fennec. That means you have to specify the application via the `-a` option. Also as issue #112 states we still miss certain features for Fennec.  Right now we only support downloading daily builds. If you need tinderbox I would appreciate if you could work on it. So I will dupe this issue against issue #112.

In case daily builds also work for you, you can get the mozinfo.js file like that:
> mozdownload -a fennec -t daily --ext mozinfo.json -p android-x86
