### ISSUE TITLE
Unable to download nightly builds of Firefox

### ISSUE THREAD

**Issue by juj** [mozilla/mozdownload#327]
Trying to run the following command on OS X:

    mozdownload --type=daily --extension=zip --date=2015-01-01

but I'm getting the error

     INFO | Retrieving list of builds from https://archive.mozilla.org/pub/mozilla.org/firefox/nightly/2015/01
    Traceback (most recent call last):
      File "/usr/local/bin/mozdownload", line 9, in <module>
        load_entry_point('mozdownload==1.17', 'console_scripts', 'mozdownload')()
      File "/Library/Python/2.7/site-packages/mozdownload/scraper.py", line 1241, in cli
        build = BUILD_TYPES[options.type](**kwargs)
      File "/Library/Python/2.7/site-packages/mozdownload/scraper.py", line 368, in __init__
        Scraper.__init__(self, *args, **kwargs)
      File "/Library/Python/2.7/site-packages/mozdownload/scraper.py", line 130, in __init__
        self.get_build_info()
      File "/Library/Python/2.7/site-packages/mozdownload/scraper.py", line 399, in get_build_info
        self.date, self.build_index)
      File "/Library/Python/2.7/site-packages/mozdownload/scraper.py", line 483, in get_build_info_for_date
        raise errors.NotFoundError(message, url)
    mozdownload.errors.NotFoundError: Folder for builds on 2015-01-01 has not been found: https://archive.mozilla.org/pub/mozilla.org/firefox/nightly/2015/01

leaving out the date parameter or trying some other date doesn't help. Is that command line wrong somehow, or perhaps some other issue?

**Comment by whimboo** [comment]
Well, you are on OS X and for that platform there is no .zip file for a build. That is only offered for win32 and win64. So what you would have to do is to add `--platform=win32` to the command and it will work. If you don't do it mozdownload will use your current platform, and will fail to find the file.
