### ISSUE TITLE
Download of latest locale can fail because we check latest-mozilla-central and not latest-mozilla-central-l10n

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#340]
I have seen today that for other locales than en-US we do not correctly check the l10n folder but the general one which only contains en-US builds:

https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/

As result a download of a locale will fail if it is not present yet in the build folder from today. This can best be tested when new Nightly builds of Firefox have been produced.

> $ mozdownload -t daily --locale ru --platform mac
 INFO | Retrieving the build status file from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
 INFO | Retrieving list of builds from https://archive.mozilla.org/pub/firefox/nightly/2015/11/
Traceback (most recent call last):
  File "/home/henrik/.virtualenvs/mozdownload/bin/mozdownload", line 9, in <module>
    load_entry_point('mozdownload==1.19', 'console_scripts', 'mozdownload')()
  File "/mozilla/code/mozdownload/mozdownload/cli.py", line 167, in cli
    build = factory.FactoryScraper(scraper_type, **kwargs)
  File "/mozilla/code/mozdownload/mozdownload/factory.py", line 118, in __init__
    scraper_types[scraper_type].__init__(self, **kwargs)
  File "/mozilla/code/mozdownload/mozdownload/scraper.py", line 365, in __init__
    Scraper.__init__(self, *args, **kwargs)
  File "/mozilla/code/mozdownload/mozdownload/scraper.py", line 123, in __init__
    self.get_build_info()
  File "/mozilla/code/mozdownload/mozdownload/scraper.py", line 396, in get_build_info
    self.date, self.build_index)
  File "/mozilla/code/mozdownload/mozdownload/scraper.py", line 481, in get_build_info_for_date
    raise errors.NotFoundError(message, url)
mozdownload.errors.NotFoundError: Folder for builds on 2015-11-02-03-02-41 has not been found: https://archive.mozilla.org/pub/firefox/nightly/2015/11/

**Comment by whimboo** [comment]
Hm, turns out that the https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/ folder does not have a status file we could use to check for the latest date. Maybe we have to change our code to simply download the files from that URL under those circumstances. It should not be done by default given that the original folder contains more than the binaries.
