### ISSUE TITLE
mozdownload doesn't handle artifact builds

### ISSUE THREAD

**Issue by EricRahm** [mozilla/mozdownload#427]
STR:

> $ mozdownload -t tinderbox --branch mozilla-inbound --revision 239f0df955d162fbad479925d8dadccf197e88f8
> INFO | Querying https://treeherder.mozilla.org for list of builds for revision: 239f0df955d162fbad479925d8dadccf197e88f8
> Traceback (most recent call last):
>   File "/home/erahm/dev/areweslimyet/tmp_env/bin/mozdownload", line 11, in <module>
>     sys.exit(cli())
>   File "/home/erahm/dev/areweslimyet/tmp_env/local/lib/python2.7/site-packages/mozdownload/cli.py", line 165, in cli
>     build = factory.FactoryScraper(scraper_type, **kwargs)
>   File "/home/erahm/dev/areweslimyet/tmp_env/local/lib/python2.7/site-packages/mozdownload/factory.py", line 125, in __init__
>     scraper_types[scraper_type].__init__(self, **kwargs)
>   File "/home/erahm/dev/areweslimyet/tmp_env/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 751, in __init__
>     Scraper.__init__(self, *args, **kwargs)
>   File "/home/erahm/dev/areweslimyet/tmp_env/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 133, in __init__
>     self._retry_check_404(self.get_build_info)
>   File "/home/erahm/dev/areweslimyet/tmp_env/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 148, in _retry_check_404
>     self._retry(func, **retry_kwargs)
>   File "/home/erahm/dev/areweslimyet/tmp_env/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 139, in _retry
>     return redo.retry(func, **retry_kwargs)
>   File "/home/erahm/dev/areweslimyet/tmp_env/local/lib/python2.7/site-packages/redo/__init__.py", line 152, in retry
>     return action(*args, **kwargs)
>   File "/home/erahm/dev/areweslimyet/tmp_env/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 765, in get_build_info
>     raise errors.NotFoundError('No builds have been found for revision', self.revision)
> mozdownload.errors.NotFoundError: No builds have been found for revision: 239f0df955d162fbad479925d8dadccf197e88f8

Note [this build exists](https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=239f0df955d162fbad479925d8dadccf197e88f8), but it happens to have been an artifact build for linux64 opt.

**Comment by EricRahm** [comment]
I thought this was related to artifact builds, but the build is there it's just listed under `tc` now.

**Comment by EricRahm** [comment]
I'm reasonably sure this is because we're [filtering on the job type being 'Build'](https://github.com/mozilla/mozdownload/blob/f07f71c178c5bc6ee631594645a3c102e0f726c5/mozdownload/treeherder.py#L89).

**Comment by EricRahm** [comment]
For background: we stopped doing buildbot builds for linux a while back (January or earlier). Buildbot builds had a `job_type_name` of 'Build' which we filter on. Taskcluster builds have a less deterministic `job_type_name` of 'build-<platform>/<build_type>'. So for example linux 64 opt is 'build-linux64/opt', linux opt is 'build-linux/opt', win32 debug is 'build-win32/debug', etc.

**Comment by EricRahm** [comment]
It also looks like mozdownload expects the job log URL to have the application name in it, which is no longer the case.

**Comment by EricRahm** [comment]
Further debugging indicates this comes down to task cluster support which is #365. Closing in favor of that.
