### ISSUE TITLE
 ValueError: 'format' in __slots__ conflicts with class variable

### ISSUE THREAD

**Issue by kenorb** [mozilla/mozdownload#443]
```
$ pip3 install mozdownload
Collecting mozdownload
  Downloading mozdownload-1.22.tar.gz
Collecting mozinfo>=0.9 (from mozdownload)
  Downloading mozinfo-0.10.tar.gz
Collecting progressbar==2.3 (from mozdownload)
  Downloading progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vp/tlt7xf791gl1_v56m0xdmrph0000gn/T/pip-build-7k8mx978/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/private/var/folders/vp/tlt7xf791gl1_v56m0xdmrph0000gn/T/pip-build-7k8mx978/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/private/var/folders/vp/tlt7xf791gl1_v56m0xdmrph0000gn/T/pip-build-7k8mx978/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace, **kwargs)
    ValueError: 'format' in __slots__ conflicts with class variable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vp/tlt7xf791gl1_v56m0xdmrph0000gn/T/pip-build-7k8mx978/progressbar/
```

**Comment by whimboo** [comment]
mozdownload is not supposed to work with Python 3 yet, sorry. In the case you want to help add support for it please have a look at issue #415. Thanks.
