### ISSUE TITLE
Downloading Fenix build with invalid platform raises an index error

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#664]
Using the following arguments from a non Android platform causes the code in DailyScraper to fail with an `IndexError` because there is no such build for such a platform.

> mozdownload -a fenix -t daily -p mac

```
Traceback (most recent call last):
  File "/Users/henrik/code/mozdownload/venv/bin/mozdownload", line 33, in <module>
    sys.exit(load_entry_point('mozdownload', 'console_scripts', 'mozdownload')())
  File "/Users/henrik/code/mozdownload/mozdownload/cli.py", line 169, in cli
    build = factory.FactoryScraper(scraper_type, **kwargs)
  File "/Users/henrik/code/mozdownload/mozdownload/factory.py", line 126, in __init__
    scraper_types[scraper_type].__init__(self, **kwargs)
  File "/Users/henrik/code/mozdownload/mozdownload/scraper.py", line 383, in __init__
    Scraper.__init__(self, *args, **kwargs)
  File "/Users/henrik/code/mozdownload/mozdownload/scraper.py", line 165, in __init__
    self._retry_check_404(self.get_build_info)
  File "/Users/henrik/code/mozdownload/mozdownload/scraper.py", line 180, in _retry_check_404
    self._retry(func, **retry_kwargs)
  File "/Users/henrik/code/mozdownload/mozdownload/scraper.py", line 171, in _retry
    return redo.retry(func, **retry_kwargs)
  File "/Users/henrik/code/mozdownload/venv/lib/python3.10/site-packages/redo-2.0.4-py3.10.egg/redo/__init__.py", line 170, in retry
    return action(*args, **kwargs)
  File "/Users/henrik/code/mozdownload/mozdownload/scraper.py", line 434, in get_build_info
    self.date = self.get_latest_build_date()
  File "/Users/henrik/code/mozdownload/mozdownload/scraper.py", line 456, in get_latest_build_date
    date = ''.join(parser.entries[-1].split('-')[:6])
IndexError: list index out of range
```

**Comment by whimboo** [comment]
PR https://github.com/mozilla/mozdownload/pull/672 fixed only one case but we should still check early when checking command line arguments if the given platform is supported by the application.

**Comment by randomicon00** [comment]
Hello @whimboo, this is the first time contributing to this code base. I would like to try my hand at it!

**Comment by whimboo** [comment]
@randomicon00 have you had the time to check the exiting code? Do you have any issues where you would need help with? Thanks

**Comment by randomicon00** [comment]
Hi @whimboo! I've missed your first message (didn't get an email notification for it). I will start working on the task. I've already had a look at the source code before interacting here and I don't have any particular question. Thanks!

**Comment by whimboo** [comment]
@randomicon00 I wanted to check in with you to see if any other issues have come up while you’ve been working on it. If you just need a bit more time, that's perfectly fine — just let me know. I want to ensure we stay in touch. Thanks!

**Comment by pandeylakshya207-max** [comment]
Hi @whimboo, I'd like to pick this up if it's still available — happy to build on the early-validation approach you mentioned (checking platform against application at CLI arg-parsing time). Let me know if @mehdiakiki is still working on it.

**Comment by whimboo** [comment]
Hey @pandeylakshya207-max! Sorry for the delayed response but I was out for a while. Happy to see your interest in working on this issue - and especially the already opened PR! I'll get to the review soon. Thanks a lot!

**Comment by pandeylakshya207-max** [comment]
No worries at all, thanks for the update! Looking forward to your review.
